sudo: required
language: bash
services:
    - docker

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::6}

install:
    - export REPO=$DOCKER_USER/kongfig
    - docker build -f Dockerfile -t $REPO:$COMMIT .

script:
    - docker images | grep -q kongfig
    - docker run $REPO:$COMMIT | grep Congratulations

after_success:
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
    - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
    - echo $REPO:$TAG:$COMMIT
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
