sudo: required
language: bash
services:
    - docker

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::6}

install:
    - export REPO=$DOCKER_USER/kongfig
    - docker build -f Dockerfile -t $REPO:$COMMIT .

script:
    - docker images | grep -q $REPO
    - docker run $REPO:$COMMIT | grep $(grep "ENV VERSION" Dockerfile | cut -d'=' -f2)

deploy:
    - provider: script
      script: chmod +x ./push_to_dockerhub.sh && ./push_to_dockerhub.sh
      skip_cleanup: true
      on:
          all_branches: true
          condition: $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG
